const models=[
{n:"Infinity Side",sub:"שולחן צד / קפה קטן",size:"Ø50–60 ס״מ · גובה 40–45 ס״מ",price:"החל מ־₪1,790",img:"https://i.etsystatic.com/28257059/r/il/6d9eb2/3347159888/il_794xN.3347159888_qe9i.jpg"},
{n:"Infinity Living",sub:"שולחן סלון מרשים",size:"100×60 ס״מ · גובה 35–40 ס״מ",price:"החל מ־₪3,490",img:"https://assets.wfcdn.com/im/23418253/resize-h800-w800%5Ecompr-r85/4185/418525122/Led%2BInfinity%2BMirror%2BCoffee%2BTable%2BFor%2BLiving%2BRoom-1261765014.jpg"},
{n:"Infinity Dining",sub:"שולחן אוכל יוקרתי",size:"180–220×90–100 ס״מ · גובה 75 ס״מ",price:"החל מ־₪7,900",img:"https://i.etsystatic.com/44061559/r/il/f3f8fe/7745576328/il_794xN.7745576328_mno1.jpg"}
];
const worlds=[["The Forest","יער אינסופי"],["The Ocean","מים אינסופיים"],["The Galaxy","חלל אינסופי"],["The Ladder","סולם אינסופי"],["The Tunnel","מנהרת אור"],["The Matrix","עולם דיגיטלי"],["The Abyss","עומק קלאסי"],["The Zen","טבע ורוגע"]];
const kids=[["Dino World","ג׳ונגל, שכבות צמחייה ודינוזאורים שנמשכים אל העומק."],["Space Mission","חללית, כוכבים וכוכבי לכת בתוך חלל אינסופי."],["Hero City","גיבור מקורי מעל עיר תלת־ממדית עמוקה ומוארת."],["Racing World","מסלול מואר ומכוניות שנעלמים אל תוך האינסוף."]];
export default function Home(){return <main dir="rtl">
<nav><div className="brand"><b>∞</b><span>Infinity Tables<small>MORE THAN A TABLE</small></span></div><div className="links"><a href="#models">דגמים</a><a href="#worlds">עולמות עיצוב</a><a href="#coming">בקרוב</a><a href="#how">איך זה עובד</a></div><a className="navcta" href="#reserve">הזמנה מוקדמת</a></nav>
<header className="hero"><div className="heroImage"></div><div className="veil"></div><div className="heroText"><h1>לא עוד שולחן.<br/><em>עולם אחר בבית שלך.</em></h1><p>רהיטים שמשלבים עיצוב, טכנולוגיה ואמנות ליצירת חוויה ויזואלית מרהיבה. כל שולחן הוא חלון לעולם אחר.</p><div className="buttons"><a className="gold" href="#models">גלה את הדגמים</a><a className="outline" href="#worlds">גלו את העולמות</a></div><div className="features"><span>◇<b>עיצוב פרימיום</b><small>מותאם אישית</small></span><span>✦<b>תאורת LED</b><small>שליטה חכמה</small></span><span>⌁<b>אספקה</b><small>עד 90 יום</small></span><span>∞<b>Worlds</b><small>מודול עולם פנימי</small></span></div></div></header>
<section id="models" className="shell modelsSection"><div className="models">{models.map(m=><article className="model" key={m.n}><div className="modelPhoto"><img src={m.img}/><div className="modelShade"></div><div className="modelName"><small>{m.sub}</small><h3>{m.n}</h3></div></div><div className="modelInfo"><span>{m.size}</span><b>{m.price}</b><a href="#reserve">עיצוב בהתאמה אישית ↗</a></div></article>)}</div></section>
<section id="worlds" className="worldSection"><div className="shell"><div className="worldHead"><div><h2>עולמות עיצוב</h2><p>בחר את העולם שמתאים לך, לכל דגם</p></div><a href="#reserve">ראה את כל העולמות ←</a></div><div className="worldGrid">{worlds.map((w,i)=><article className={"world w"+i} key={w[0]}><div className="depth"><i></i><i></i><i></i><i></i></div><div><h3>{w[0]}</h3><span>{w[1]}</span></div></article>)}</div><div className="custom">+ YOUR WORLD <span>עיצוב אישי לפי סיפור, חלל או רעיון משלכם</span></div></div></section>
<section className="manifest compact"><div className="shell"><div className="ey">THE IDEA</div><h2>אנחנו לא מוכרים<br/><em>אפקט של מראה.</em><br/>אנחנו בונים עולמות.</h2><p>כל World מתחיל כסצנה פיזית אמיתית: קירות, צמחייה, דמויות, מים, אור או אובייקטים מיניאטוריים. מערכת אופטית הופכת כמה סנטימטרים של בנייה לעומק שנראה כמו מטרים.</p></div></section>
<section id="coming" className="shell coming"><div className="sectionTitle"><div><div className="ey">WHAT'S NEXT</div><h2>וזו רק ההתחלה.</h2></div><p>שתי קולקציות שנמצאות בפיתוח ומראות לאן Infinity Worlds יכול להגיע מעבר לקולקציית ההשקה.</p></div><div className="future"><article className="exodus"><img src="https://watermarkwaves.com/cdn/shop/articles/10_Facts_About_the_Parting_of_the_Red_Sea_in_the_Bible.png?v=1767139839&width=1536"/><div className="fshade"></div><div className="fcopy"><span>ART COLLECTION · COMING SOON</span><h3>THE EXODUS</h3><p>חציית ים סוף בתוך שולחן אמנות: קירות מים מוארים, דרך במדבר ושיירה שנמשכת אל תוך האופק.</p></div></article><article className="kidsHero"><img src="https://alderlight.com/img/image3_shoebox-theatre-ideas_space-odyssey.jpg"/><div className="fshade"></div><div className="fcopy"><span>INFINITY KIDS · COMING SOON</span><h3>הדמיון שלהם.<br/>העולם שלהם.</h3><p>עולמות צבעוניים לחדרי ילדים עם אותה אשליית עומק, אבל שפה שמיועדת להם.</p></div></article></div><div className="kidsGrid">{kids.map((k,i)=><article className={"kid kid"+i} key={k[0]}><span>COMING SOON</span><h3>{k[0]}</h3><p>{k[1]}</p></article>)}</div></section>
<section id="how" className="how"><div className="shell"><div className="sectionTitle"><div><div className="ey">BEHIND THE ILLUSION</div><h2>נראה בלתי אפשרי.<br/>בנוי בעולם האמיתי.</h2></div></div><div className="steps"><div><b>01</b><h3>דיאורמה פיזית</h3><p>אובייקטים וחומרים אמיתיים בתוך הרהיט.</p></div><div><b>02</b><h3>Infinity Optics</h3><p>שכבות אופטיות יוצרות המשכיות ועומק דרמטי.</p></div><div><b>03</b><h3>אור כחלק מהסיפור</h3><p>התאורה מעצבת את העולם ולא רק מקשטת אותו.</p></div><div><b>04</b><h3>שליטה חכמה</h3><p>מצבי תאורה ושליטה פשוטה ונוחה.</p></div></div></div></section>
<section id="reserve" className="reserve shell"><div><div className="ey">EARLY ACCESS</div><h2>העולם הראשון שלכם<br/>מתחיל כאן.</h2><p>שריון מוקדם ב־₪200. בחרו דגם, בחרו World, וקבלו עדכון ראשון כשהייצור נפתח.</p><a className="gold" href="mailto:hello@infinityworlds.co">שריינו מקום בקולקציית ההשקה</a></div></section>
<footer className="shell"><div className="brand"><b>∞</b><span>INFINITY WORLDS<small>MORE THAN A TABLE</small></span></div><span>CONCEPT COLLECTION · 2026</span></footer>
</main>}