const products=[
{n:"DEEP OCEAN",sub:"WORLD 01",img:"https://luxarts.net/wp-content/uploads/2025/01/dolphin-epoxy-coffee-tables-1.jpeg",copy:"עולם תת־ימי שנבנה בתוך הרהיט, עם שכבות עומק, תאורה ופרטים פיזיים שממשיכים אל מעבר לזכוכית."},
{n:"INFINITY LIVING",sub:"WORLD 02",img:"https://assets.wfcdn.com/im/19238025/compr-r85/4175/417514676/Led%2BInfinity%2BMirror%2BCoffee%2BTable%2BFor%2BLiving%2BRoom.jpg",copy:"רהיט סלון נקי ויוקרתי שבמרכזו חלל אופטי עמוק. ביום הוא שולחן, בלילה הוא מוקד של כל החדר."},
{n:"SECRET GARDEN",sub:"WORLD 03",img:"https://i.etsystatic.com/44061559/r/il/f3f8fe/7745576328/il_794xN.7745576328_mno1.jpg",copy:"דיאורמה ירוקה עם גשר, צמחייה ומים, עולם מיניאטורי אמיתי שמקבל עומק בלתי אפשרי דרך האופטיקה."}
];
export default function Home(){return <main>
<nav><div className="brand"><span>∞</span> INFINITY WORLDS</div><div className="links"><a href="#collection">הקולקציה</a><a href="#coming">בקרוב</a><a href="#technology">איך זה עובד</a><a href="#reserve">שריון מוקדם</a></div><a className="navcta" href="#reserve">השקה מוקדמת</a></nav>
<header className="hero"><img className="heroImg" src="https://assets.wfcdn.com/im/23418253/resize-h800-w800%5Ecompr-r85/4185/418525122/Led%2BInfinity%2BMirror%2BCoffee%2BTable%2BFor%2BLiving%2BRoom-1261765014.jpg"/><div className="heroShade"></div><div className="heroCopy"><div className="kicker">OBJECTS THAT OPEN OTHER WORLDS</div><h1>לא עוד שולחן.<br/><em>עולם אחר בבית שלך.</em></h1><p>רהיטי Infinity שמחברים דיאורמה פיזית, אור ואשליה אופטית כדי ליצור חלל שנראה עמוק בהרבה מהרהיט עצמו.</p><div className="actions"><a className="primary" href="#collection">גלו את העולמות</a><a className="ghost" href="#reserve">שריינו ב־₪200</a></div><div className="proof"><span><b>01</b> קולקציית השקה</span><span><b>03</b> עולמות ראשונים</span><span><b>∞</b> אפשרויות בהמשך</span></div></div></header>
<section id="collection" className="section"><div className="sectionHead"><div><div className="kicker">FOUNDERS COLLECTION</div><h2>שלושת הראשונים.</h2></div><p>לא ריבועים ולא ספירלות. כל World הוא אובייקט אמיתי בתוך חלל אמיתי, עם חומר, תאורה וסיפור משלו.</p></div><div className="products">{products.map(w=><article className="product" key={w.n}><div className="photo"><img src={w.img}/><span>{w.sub}</span></div><div className="productCopy"><small>{w.sub}</small><h3>{w.n}</h3><p>{w.copy}</p><a href="#reserve">DISCOVER THE WORLD ↗</a></div></article>)}</div></section>
<section id="coming" className="future section"><div className="sectionHead"><div><div className="kicker">NEXT WORLDS</div><h2>וזו רק ההתחלה.</h2></div><p>השלב הבא מרחיב את Infinity Worlds מרהיטים לעולמות אמנותיים שלמים.</p></div><div className="futureGrid"><article className="futureCard exodus"><img src="https://watermarkwaves.com/cdn/shop/articles/10_Facts_About_the_Parting_of_the_Red_Sea_in_the_Bible.png?v=1767139839&width=1536"/><div className="overlay"></div><div className="futureText"><span>ART COLLECTION · COMING SOON</span><h3>THE EXODUS</h3><p>חציית ים סוף כיצירת Infinity: קירות מים, דרך מוארת ושיירה שנמשכת אל האופק.</p></div></article><article className="futureCard kids"><img src="https://alderlight.com/img/image3_shoebox-theatre-ideas_space-odyssey.jpg"/><div className="overlay"></div><div className="futureText"><span>INFINITY KIDS · COMING SOON</span><h3>SMALL WORLDS.<br/>ENDLESS IMAGINATION.</h3><p>Space Mission · Dino World · Racing City. דיאורמות פיזיות מקוריות לילדים, לא עוד אפקט גרפי.</p></div></article></div></section>
<section id="technology" className="statement"><div className="kicker">BUILT, NOT PRINTED</div><h2>בונים 15 ס״מ.<br/>חווים <em>15 מטר.</em></h2><p>בתוך כל World נמצאת סצנה פיזית אמיתית. מראות, שכבות אופטיות ותאורה מחזירות אותה שוב ושוב ויוצרות עומק שנראה בלתי אפשרי.</p><div className="how"><div><b>01</b><strong>דיאורמה פיזית</strong><span>חומרים, דמויות ואובייקטים אמיתיים.</span></div><div><b>02</b><strong>Infinity Optics</strong><span>שכבות מראה שמכפילות את החלל.</span></div><div><b>03</b><strong>Integrated Light</strong><span>תאורה כחלק מהסצנה עצמה.</span></div><div><b>04</b><strong>Custom Worlds</strong><span>כל עולם יכול להפוך ליצירה אישית.</span></div></div></section>
<section id="reserve" className="reserve"><div className="kicker">EARLY ACCESS</div><h2>רוצים להיות בין הראשונים?</h2><p>שריון מוקדם ב־₪200 בלבד. השאירו מקום בקולקציית ההשקה וקבלו עדכון ראשון כשהייצור נפתח.</p><a className="primary" href="mailto:hello@infinityworlds.co">שריינו מקום</a><small>Concept collection · visual references shown for product direction</small></section>
<footer><div className="brand"><span>∞</span> INFINITY WORLDS</div><p>DESIGNED IN ISRAEL · BUILT TO FEEL IMPOSSIBLE</p></footer>
</main>}